#!/bin/bash

ln -s ~/repo/ubiquitous/vimrc    ~/.vimrc
ln -s ~/repo/ubiquitous/bashrc   ~/.bashrc
ln -s ~/repo/ubiquitous/profile  ~/.bash_profile
ln -s ~/repo/ubiquitous/inputrc  ~/.inputrc
ln -s ~/repo/ubiquitous/laptop   ~/.bash_laptop

ln -s ~/repo/ubiquitous/y/bashrc	~/.ybashrc
ln -s ~/repo/ubiquitous/y/screen	~/.screen
ln -s ~/repo/ubiquitous/y/go  	~/.go
ln -s ~/repo/ubiquitous/y/deploy	~/.deploy