# Source global definitions
if [ -f /etc/bashrc ]; then
   . /etc/bashrc
fi

# CVS
export CVSROOT=vault.yahoo.com:/CVSROOT
export CVSTOP=/homes/username/dev
export CVS_RSH=yssh

# yssh config
if [ -x /usr/local/bin/yssh ]; then
  # SVN
  export SVN_SSH=/usr/local/bin/yssh
  alias ssh=yssh
  alias scp=yscp
fi

if [ -x /usr/local/bin/yssh-find-agent ]; then
  export SSH_AUTH_SOCK=`/usr/local/bin/yssh-find-agent`
fi

export SVNROOT=svn+ssh://svn.corp.yahoo.com/

export PATH=/home/y/bin:/home/y/libexec/:$HOME/bin:${PATH}

alias el='tail -f /home/y/logs/yapache/error'
alias cdh='cd /home/y/share/htdocs'
alias cds='cd /home/y/share'

alias go='~/.go '
alias deploy='~/.deploy '
alias update='~/.go '
alias s='screen -xU'
alias sn='screen'
alias sx='pkill screen'

# developement
alias pkg='rm *.tgz; yinst_create -t link --clean *yicf; yinst i *.tgz;'

# igor
alias ir='yinst restore -igor '
alias irn='yinst restore -n -igor '

# dev
alias vm1='ssh floweridea-vm1.miami.corp.yahoo.com'
alias vm2='ssh floweridea-vm2.miami.corp.yahoo.com'

# build
export REMOTE_WEBDEV=floweridea-vm2.miami.corp.yahoo.com:/home/caridy/src/searchfe/projects/web/src/webdev
export LOCAL_WEBDEV=/Users/caridy/dev_svn/search/web/src/webdev