# Source global definitions
if [ -f /etc/bashrc ]; then
   . /etc/bashrc
fi

# yssh config
if [ -x /usr/local/bin/yssh ]; then
  # SVN
  export SVN_SSH=/usr/local/bin/yssh
  alias ssh=yssh
  alias scp=yscp
fi

if [ -x /usr/local/bin/yssh-find-agent ]; then
  export SSH_AUTH_SOCK=`/usr/local/bin/yssh-find-agent`
fi

export SVNROOT=svn+ssh://svn.corp.yahoo.com/

export PATH=/home/y/bin:/home/y/libexec/:$HOME/bin:${PATH}

alias el='tail -f /home/y/logs/yapache/error'
alias cdh='cd /home/y/share/htdocs'
alias cds='cd /home/y/share'

alias go='~/.go '
alias deploy='~/.deploy '
alias update='~/.go '
alias s='screen -xU'
alias sn='screen'
alias sx='pkill screen'
