#!/bin/bash

############################ template.sh ###########################
# Author Name | caridy@yahoo-inc.com
# Copyright 2010 Caridy Patino
####################################################################

yinst i -br test ysubversion
yinst i git_svn_y
yinst i ports/screen
yinst i vim7 -br current

mkdir -p ~/repository/git ~/repository/svn
cd ~/repository/git && git clone git://github.com/scrooloose/nerdtree.git
cd ~/repository && git clone git://github.com/caridy/ubiquitous.git

# symlink the config files
~/repository/ubiquitous/ubiquitize
         
# install nerdtree
mkdir -p ~/.vim/plugin
cp ~/repository/nerdtree/plugin/NERD_tree.vim ~/.vim/plugin/

# allow for symlink development
echo "open_basedir = \${open_basedir}:/home/caridy/ > /home/y/etc/php/caridy.ini"
yinst restart yapache
