#!/bin/bash

############################ deploy.sh ###########################
# Author Name | caridy@yahoo-inc.com
# Copyright 2010 Caridy Patino
####################################################################

yinst i ysubversion git_svn_y vim7 -br test

mkdir -p ~/repository/git ~/repository/svn
cd ~/repository/git && git clone git://github.com/scrooloose/nerdtree.git
cd ~/repository && git clone git://github.com/caridy/ubiquitous.git

# symlink the config files
~/repository/ubiquitous/ubiquitize
         
# install nerdtree
mkdir -p ~/.vim/plugin
cp ~/repository/git/nerdtree/plugin/NERD_tree.vim ~/.vim/plugin/

# allow for symlink development
if [ -e /home/y/etc/php/ ]; then
    echo "open_basedir = \${open_basedir}:/home/caridy/ > /home/y/etc/php/caridy.ini"
    yinst restart yapache
fi